import Head from "next/head";
import { useState, useContext } from "react";
import React from "react";

import ContactForm from "@/components/ContactForm/ContactForm";

import Splash from "./splash/";
export const MyContext = React.createContext();

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
				<link
					href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<Splash />
		</>
	);
}
